import Link from 'next/link';
import Header from '@/components/Header';

export const metadata = {
  title: 'Terms of Service | Free Pay Stub Generator',
  description: 'Terms of Service for Free Pay Stub Generator. Read our terms and conditions for using our pay stub generation service.',
  openGraph: {
    title: 'Terms of Service | Free Pay Stub Generator',
    description: 'Terms of Service for Free Pay Stub Generator. Read our terms and conditions.',
    url: 'https://freepaystubgen.com/terms',
  },
  alternates: {
    canonical: 'https://freepaystubgen.com/terms',
  },
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-stone-50 flex flex-col">
      <Header />

      {/* Main Content */}
      <main className="flex-1 max-w-3xl mx-auto px-4 py-8 sm:py-12 w-full">
        <div className="bg-white rounded-2xl shadow-lg shadow-stone-200/50 p-6 sm:p-10">
          <h1 className="text-2xl sm:text-3xl font-bold text-stone-800 mb-2">Terms of Service</h1>
          <p className="text-stone-500 text-sm mb-8">Last updated: January 2026</p>

          <div className="prose prose-stone max-w-none space-y-6 text-stone-600">
            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">1. Acceptance of Terms</h2>
              <p className="text-sm leading-relaxed">
                By accessing and using Free Pay Stub Generator, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">2. Description of Service</h2>
              <p className="text-sm leading-relaxed">
                Free Pay Stub Generator provides a free online tool for creating pay stub documents. The service includes tax calculations based on current federal and state tax rates for all 50 US states.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">3. Intended Use</h2>
              <p className="text-sm leading-relaxed mb-3">
                This service is intended for:
              </p>
              <ul className="list-disc list-inside text-sm space-y-2 ml-2">
                <li>Small business owners creating pay stubs for employees</li>
                <li>Self-employed individuals documenting income</li>
                <li>Educational and planning purposes</li>
                <li>Personal record-keeping</li>
              </ul>
              <p className="text-sm leading-relaxed mt-3 p-3 bg-amber-50 border border-amber-200 rounded-lg">
                <strong className="text-amber-800">Important:</strong> Pay stubs generated by this service should accurately reflect actual wages paid. Creating fraudulent pay stubs for deceptive purposes (such as loan applications, rental applications, or other fraudulent activities) is illegal and strictly prohibited.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">4. Tax Calculation Disclaimer</h2>
              <p className="text-sm leading-relaxed p-3 bg-stone-100 border border-stone-200 rounded-lg">
                <strong>The tax calculations provided by this service are estimates only.</strong> While we strive to maintain accurate and up-to-date tax rates, we cannot guarantee the accuracy of all calculations. Tax laws change frequently, and individual circumstances vary. Always consult with a qualified tax professional or accountant for official tax advice and verification.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">5. User Responsibilities</h2>
              <p className="text-sm leading-relaxed">
                By using this service, you agree to:
              </p>
              <ul className="list-disc list-inside text-sm space-y-2 ml-2 mt-2">
                <li>Provide accurate information when generating pay stubs</li>
                <li>Use generated documents only for lawful purposes</li>
                <li>Verify all calculations with appropriate professionals</li>
                <li>Comply with all applicable federal, state, and local laws</li>
                <li>Not use the service for fraudulent or deceptive purposes</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">6. Limitation of Liability</h2>
              <p className="text-sm leading-relaxed">
                Free Pay Stub Generator is provided &quot;as is&quot; without warranties of any kind. We are not liable for:
              </p>
              <ul className="list-disc list-inside text-sm space-y-2 ml-2 mt-2">
                <li>Errors or inaccuracies in tax calculations</li>
                <li>Any damages resulting from the use of generated documents</li>
                <li>Loss of data or business interruption</li>
                <li>Any indirect, incidental, or consequential damages</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">7. Intellectual Property</h2>
              <p className="text-sm leading-relaxed">
                The Free Pay Stub Generator service, including its design, features, and content, is protected by intellectual property laws. You may not copy, modify, or distribute any part of the service without permission.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">8. Modifications to Service</h2>
              <p className="text-sm leading-relaxed">
                We reserve the right to modify, suspend, or discontinue the service at any time without notice. We may also update these Terms of Service periodically.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">9. Governing Law</h2>
              <p className="text-sm leading-relaxed">
                These Terms of Service are governed by the laws of the United States. Any disputes shall be resolved in accordance with applicable state and federal laws.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-stone-800 mb-3">10. Contact</h2>
              <p className="text-sm leading-relaxed">
                For questions about these Terms of Service, please visit our <Link href="/contact" className="text-amber-600 hover:text-amber-700 underline">Contact page</Link>.
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-white/50 border-t border-stone-100 mt-auto">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex flex-wrap justify-center gap-4 text-xs text-stone-500">
            <Link href="/" className="hover:text-stone-700">Home</Link>
            <Link href="/about" className="hover:text-stone-700">About</Link>
            <Link href="/contact" className="hover:text-stone-700">Contact</Link>
            <Link href="/privacy" className="hover:text-stone-700">Privacy Policy</Link>
            <Link href="/terms" className="text-stone-700 font-medium">Terms of Service</Link>
          </div>
          <p className="text-center text-xs text-stone-400 mt-3">
            &copy; {new Date().getFullYear()} Free Pay Stub Generator. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
